import type { TemplateBase } from '~/bootstrap/templates/application/service/template.types'
import { RuleGroupType } from '~/modules/rule-group/application/rule-group.type'

export const shadcnTemplate: TemplateBase = {
  name: 'Shadcn Template',
  slug: 'shadcn',
  groups: [
    {
      key: 'styles',
      name: 'Styles',
      type: RuleGroupType.category,
      description: null,
      metadata: null,
      orderIndex: 0,
      children: [
        {
          key: 'colors',
          name: 'Colors',
          type: RuleGroupType.category,
          orderIndex: 0,
          description: null,
          metadata: null,
          children: [
            {
              key: 'color-foreground',
              name: 'Foreground',
              type: RuleGroupType.token,
              orderIndex: 0,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 96% 9%)',
                css_var: '--foreground',
              },
            },
            {
              key: 'color-background',
              name: 'Background',
              type: RuleGroupType.token,
              orderIndex: 1,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(0 0% 100%)',
                css_var: '--background',
              },
            },
            {
              key: 'color-card',
              name: 'Card',
              type: RuleGroupType.token,
              orderIndex: 2,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(0 0% 100%)',
                css_var: '--card',
              },
            },
            {
              key: 'color-card-foreground',
              name: 'Card Foreground',
              type: RuleGroupType.token,
              orderIndex: 3,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 96% 9%)',
                css_var: '--card-foreground',
              },
            },
            {
              key: 'color-popover',
              name: 'Popover',
              type: RuleGroupType.token,
              orderIndex: 4,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(0 0% 100%)',
                css_var: '--popover',
              },
            },
            {
              key: 'color-popover-foreground',
              name: 'Popover Foreground',
              type: RuleGroupType.token,
              orderIndex: 5,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 96% 9%)',
                css_var: '--popover-foreground',
              },
            },
            {
              key: 'color-primary',
              name: 'Primary',
              type: RuleGroupType.token,
              orderIndex: 6,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(229 84% 51%)',
                css_var: '--primary',
              },
              rules: [
                {
                  key: 'color-primary-rule-1',
                  name: 'Primary action color',
                  body: 'Use primary for main CTAs and key interactive elements.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'color-primary-foreground',
              name: 'Primary Foreground',
              type: RuleGroupType.token,
              orderIndex: 7,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 100% 96%)',
                css_var: '--primary-foreground',
              },
            },
            {
              key: 'color-secondary',
              name: 'Secondary',
              type: RuleGroupType.token,
              orderIndex: 8,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(231 70% 95%)',
                css_var: '--secondary',
              },
              rules: [
                {
                  key: 'color-secondary-rule-1',
                  name: 'Secondary actions',
                  body: 'Use secondary for less prominent actions and backgrounds.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'color-secondary-foreground',
              name: 'Secondary Foreground',
              type: RuleGroupType.token,
              orderIndex: 9,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(229 84% 51%)',
                css_var: '--secondary-foreground',
              },
            },
            {
              key: 'color-muted',
              name: 'Muted',
              type: RuleGroupType.token,
              orderIndex: 10,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 80% 99%)',
                css_var: '--muted',
              },
              rules: [
                {
                  key: 'color-muted-rule-1',
                  name: 'Subtle backgrounds',
                  body: 'Use muted for subtle backgrounds and disabled states.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'color-muted-foreground',
              name: 'Muted Foreground',
              type: RuleGroupType.token,
              orderIndex: 11,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 17% 50%)',
                css_var: '--muted-foreground',
              },
            },
            {
              key: 'color-accent',
              name: 'Accent',
              type: RuleGroupType.token,
              orderIndex: 12,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(72 100% 93%)',
                css_var: '--accent',
              },
              rules: [
                {
                  key: 'color-accent-rule-1',
                  name: 'Accent highlights',
                  body: 'Use accent for highlights and emphasis.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'color-accent-foreground',
              name: 'Accent Foreground',
              type: RuleGroupType.token,
              orderIndex: 13,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(73 23% 24%)',
                css_var: '--accent-foreground',
              },
            },
            {
              key: 'color-info',
              name: 'Info',
              type: RuleGroupType.token,
              orderIndex: 14,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(201 98% 32%)',
                css_var: '--info',
              },
            },
            {
              key: 'color-info-foreground',
              name: 'Info Foreground',
              type: RuleGroupType.token,
              orderIndex: 15,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(204 100% 97%)',
                css_var: '--info-foreground',
              },
            },
            {
              key: 'color-success',
              name: 'Success',
              type: RuleGroupType.token,
              orderIndex: 16,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(155 90% 24%)',
                css_var: '--success',
              },
            },
            {
              key: 'color-success-foreground',
              name: 'Success Foreground',
              type: RuleGroupType.token,
              orderIndex: 17,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(145 81% 96%)',
                css_var: '--success-foreground',
              },
            },
            {
              key: 'color-warning',
              name: 'Warning',
              type: RuleGroupType.token,
              orderIndex: 18,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(22 92% 37%)',
                css_var: '--warning',
              },
            },
            {
              key: 'color-warning-foreground',
              name: 'Warning Foreground',
              type: RuleGroupType.token,
              orderIndex: 19,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(45 100% 96%)',
                css_var: '--warning-foreground',
              },
            },
            {
              key: 'color-destructive',
              name: 'Destructive',
              type: RuleGroupType.token,
              orderIndex: 20,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(357 100% 45%)',
                css_var: '--destructive',
              },
              rules: [
                {
                  key: 'color-destructive-rule-1',
                  name: 'Destructive actions only',
                  body: 'Use destructive color only for irreversible or dangerous actions.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
                {
                  key: 'color-destructive-rule-2',
                  name: 'Confirmation required',
                  body: 'Always pair destructive actions with a confirmation step.',
                  orderIndex: 1,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'color-border',
              name: 'Border',
              type: RuleGroupType.token,
              orderIndex: 21,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 14% 23% / 7%)',
                css_var: '--border',
              },
            },
            {
              key: 'color-input',
              name: 'Input',
              type: RuleGroupType.token,
              orderIndex: 22,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 26% 86%)',
                css_var: '--input',
              },
            },
            {
              key: 'color-ring',
              name: 'Ring',
              type: RuleGroupType.token,
              orderIndex: 23,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 39% 44%)',
                css_var: '--ring',
              },
            },
            {
              key: 'color-chart-1',
              name: 'Chart 1',
              type: RuleGroupType.token,
              orderIndex: 24,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(211 100% 78%)',
                css_var: '--chart-1',
              },
            },
            {
              key: 'color-chart-2',
              name: 'Chart 2',
              type: RuleGroupType.token,
              orderIndex: 25,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(216 100% 58%)',
                css_var: '--chart-2',
              },
            },
            {
              key: 'color-chart-3',
              name: 'Chart 3',
              type: RuleGroupType.token,
              orderIndex: 26,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(221 97% 54%)',
                css_var: '--chart-3',
              },
            },
            {
              key: 'color-chart-4',
              name: 'Chart 4',
              type: RuleGroupType.token,
              orderIndex: 27,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(225 84% 49%)',
                css_var: '--chart-4',
              },
            },
            {
              key: 'color-chart-5',
              name: 'Chart 5',
              type: RuleGroupType.token,
              orderIndex: 28,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(227 76% 41%)',
                css_var: '--chart-5',
              },
            },
            {
              key: 'color-sidebar',
              name: 'Sidebar',
              type: RuleGroupType.token,
              orderIndex: 29,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(231 90% 97%)',
                css_var: '--sidebar',
              },
            },
            {
              key: 'color-sidebar-foreground',
              name: 'Sidebar Foreground',
              type: RuleGroupType.token,
              orderIndex: 30,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(234 96% 9%)',
                css_var: '--sidebar-foreground',
              },
            },
            {
              key: 'color-sidebar-primary',
              name: 'Sidebar Primary',
              type: RuleGroupType.token,
              orderIndex: 31,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(229 84% 51%)',
                css_var: '--sidebar-primary',
              },
            },
            {
              key: 'color-sidebar-primary-foreground',
              name: 'Sidebar Primary Foreground',
              type: RuleGroupType.token,
              orderIndex: 32,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 100% 96%)',
                css_var: '--sidebar-primary-foreground',
              },
            },
            {
              key: 'color-sidebar-accent',
              name: 'Sidebar Accent',
              type: RuleGroupType.token,
              orderIndex: 33,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(73 100% 96%)',
                css_var: '--sidebar-accent',
              },
            },
            {
              key: 'color-sidebar-accent-foreground',
              name: 'Sidebar Accent Foreground',
              type: RuleGroupType.token,
              orderIndex: 34,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(72 100% 12%)',
                css_var: '--sidebar-accent-foreground',
              },
            },
            {
              key: 'color-sidebar-border',
              name: 'Sidebar Border',
              type: RuleGroupType.token,
              orderIndex: 35,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(232 60% 85%)',
                css_var: '--sidebar-border',
              },
            },
            {
              key: 'color-sidebar-ring',
              name: 'Sidebar Ring',
              type: RuleGroupType.token,
              orderIndex: 36,
              description: null,
              metadata: {
                token_type: 'color',
                value: 'hsl(233 27% 53%)',
                css_var: '--sidebar-ring',
              },
            },
          ],
        },
        {
          key: 'typography',
          name: 'Typography',
          type: RuleGroupType.category,
          orderIndex: 1,
          description: null,
          metadata: null,
          children: [
            {
              key: 'font-sans',
              name: 'Font Sans',
              type: RuleGroupType.token,
              orderIndex: 0,
              description: null,
              metadata: {
                token_type: 'font',
                value: 'Geist',
                css_var: '--font-sans',
              },
            },
            {
              key: 'font-mono',
              name: 'Font Mono',
              type: RuleGroupType.token,
              orderIndex: 1,
              description: null,
              metadata: {
                token_type: 'font',
                value: 'Geist Mono',
                css_var: '--font-mono',
              },
            },
            {
              key: 'text-xs',
              name: 'text-xs',
              type: RuleGroupType.token,
              orderIndex: 2,
              description: null,
              metadata: {
                token_type: 'typography',
                value: '0.75rem',
                line_height: '1rem',
                css_var: '--font-size-xs',
              },
              rules: [
                {
                  key: 'text-xs-rule-1',
                  name: 'Small text only',
                  body: 'Use text-xs for captions and helper text only.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'text-sm',
              name: 'text-sm',
              type: RuleGroupType.token,
              orderIndex: 3,
              description: null,
              metadata: {
                token_type: 'typography',
                value: '0.875rem',
                line_height: '1.25rem',
                css_var: '--font-size-sm',
              },
              rules: [
                {
                  key: 'text-sm-rule-1',
                  name: 'Body text',
                  body: 'Use text-sm for body text and secondary content.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'text-base',
              name: 'text-base',
              type: RuleGroupType.token,
              orderIndex: 4,
              description: null,
              metadata: {
                token_type: 'typography',
                value: '1rem',
                line_height: '1.5rem',
                css_var: '--font-size-base',
              },
              rules: [
                {
                  key: 'text-base-rule-1',
                  name: 'Default size',
                  body: 'Use text-base as the default font size for most content.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'text-lg',
              name: 'text-lg',
              type: RuleGroupType.token,
              orderIndex: 5,
              description: null,
              metadata: {
                token_type: 'typography',
                value: '1.125rem',
                line_height: '1.75rem',
                css_var: '--font-size-lg',
              },
              rules: [
                {
                  key: 'text-lg-rule-1',
                  name: 'Subheadings',
                  body: 'Use text-lg for subheadings in card layouts.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
          ],
        },
        {
          key: 'radius',
          name: 'Radius',
          type: RuleGroupType.category,
          orderIndex: 2,
          description: null,
          metadata: null,
          children: [
            {
              key: 'radius-base',
              name: 'Radius',
              type: RuleGroupType.token,
              orderIndex: 0,
              description: null,
              metadata: {
                token_type: 'radius',
                value: '0.625rem',
                css_var: '--radius',
              },
            },
            {
              key: 'radius-sm',
              name: 'radius-sm',
              type: RuleGroupType.token,
              orderIndex: 1,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) - 4px)',
                css_var: '--radius-smasdasd',
              },
              rules: [
                {
                  key: 'radius-sm-rule-1',
                  name: 'Small elements',
                  body: 'Use radius-sm for small interactive elements like badges.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'radius-md',
              name: 'radius-md',
              type: RuleGroupType.token,
              orderIndex: 2,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) - 2px)',
                css_var: '--radius-md',
              },
              rules: [
                {
                  key: 'radius-md-rule-1',
                  name: 'Default radius',
                  body: 'Use radius-md as the default border radius for most components.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'radius-lg',
              name: 'radius-lg',
              type: RuleGroupType.token,
              orderIndex: 3,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'var(--radius)',
                css_var: '--radius-lg',
              },
              rules: [
                {
                  key: 'radius-lg-rule-1',
                  name: 'Cards and modals',
                  body: 'Use radius-lg for cards and modals, never for buttons.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'radius-xl',
              name: 'radius-xl',
              type: RuleGroupType.token,
              orderIndex: 4,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) + 4px)',
                css_var: '--radius-xl',
              },
            },
            {
              key: 'radius-2xl',
              name: 'radius-2xl',
              type: RuleGroupType.token,
              orderIndex: 5,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) + 8px)',
                css_var: '--radius-2xl',
              },
            },
            {
              key: 'radius-3xl',
              name: 'radius-3xl',
              type: RuleGroupType.token,
              orderIndex: 6,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) + 12px)',
                css_var: '--radius-3xl',
              },
            },
            {
              key: 'radius-4xl',
              name: 'radius-4xl',
              type: RuleGroupType.token,
              orderIndex: 7,
              description: null,
              metadata: {
                token_type: 'radius',
                value: 'calc(var(--radius) + 16px)',
                css_var: '--radius-4xl',
              },
            },
          ],
        },
        {
          key: 'shadows',
          name: 'Shadows',
          type: RuleGroupType.category,
          orderIndex: 3,
          description: null,
          metadata: null,
          children: [
            {
              key: 'shadow-sm',
              name: 'shadow-sm',
              type: RuleGroupType.token,
              orderIndex: 0,
              description: null,
              metadata: {
                token_type: 'shadow',
                value: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                css_var: '--shadow-sm',
              },
              rules: [
                {
                  key: 'shadow-sm-rule-1',
                  name: 'Subtle elevation',
                  body: 'Use shadow-sm for subtle elevation on hover states.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'shadow-md',
              name: 'shadow-md',
              type: RuleGroupType.token,
              orderIndex: 1,
              description: null,
              metadata: {
                token_type: 'shadow',
                value: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                css_var: '--shadow-md',
              },
              rules: [
                {
                  key: 'shadow-md-rule-1',
                  name: 'Elevated surfaces',
                  body: 'Use shadow-md for elevated surfaces like dropdowns and popovers.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'shadow-lg',
              name: 'shadow-lg',
              type: RuleGroupType.token,
              orderIndex: 2,
              description: null,
              metadata: {
                token_type: 'shadow',
                value: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
                css_var: '--shadow-lg',
              },
              rules: [
                {
                  key: 'shadow-lg-rule-1',
                  name: 'Modals and dialogs',
                  body: 'Use shadow-lg for modals and dialogs to create depth.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      key: 'components',
      name: 'Components',
      type: RuleGroupType.category,
      orderIndex: 1,
      description: null,
      metadata: null,
      children: [
        {
          key: 'button',
          name: 'Button',
          type: RuleGroupType.component,
          orderIndex: 0,
          description: null,
          metadata: null,
          rules: [
            {
              key: 'button-rule-1',
              name: 'Always include a visible text label',
              body: 'Buttons must have a visible text label for accessibility.',
              orderIndex: 0,
              description: null,
              metadata: null,
            },
            {
              key: 'button-rule-2',
              name: 'Max one primary button per view',
              body: 'Limit to one primary button per view to maintain visual hierarchy.',
              orderIndex: 1,
              description: null,
              metadata: null,
            },
          ],
          children: [
            {
              key: 'button-destructive',
              name: 'Destructive',
              type: RuleGroupType.variant,
              orderIndex: 0,
              description: null,
              metadata: null,
              rules: [
                {
                  key: 'button-destructive-rule-1',
                  name: 'Only for irreversible actions',
                  body: 'Use destructive variant only for irreversible or dangerous actions.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
                {
                  key: 'button-destructive-rule-2',
                  name: 'Must include confirmation step',
                  body: 'Destructive buttons must include a confirmation step before execution.',
                  orderIndex: 1,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'button-ghost',
              name: 'Ghost',
              type: RuleGroupType.variant,
              orderIndex: 1,
              description: null,
              metadata: null,
              rules: [
                {
                  key: 'button-ghost-rule-1',
                  name: 'Secondary actions in toolbars',
                  body: 'Use ghost variant for secondary actions in toolbars and navigation.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
            {
              key: 'button-outline',
              name: 'Outline',
              type: RuleGroupType.variant,
              orderIndex: 2,
              description: null,
              metadata: null,
              rules: [
                {
                  key: 'button-outline-rule-1',
                  name: 'Secondary actions',
                  body: 'Use outline variant for secondary actions that need visual weight.',
                  orderIndex: 0,
                  description: null,
                  metadata: null,
                },
              ],
            },
          ],
        },
        {
          key: 'accordion',
          name: 'Accordion',
          type: RuleGroupType.component,
          orderIndex: 1,
          description: null,
          metadata: null,
          rules: [
            {
              key: 'accordion-rule-1',
              name: 'Collapsible content sections',
              body: 'Use accordion for collapsible content sections to save space.',
              orderIndex: 0,
              description: null,
              metadata: null,
            },
          ],
        },
        {
          key: 'alert',
          name: 'Alert',
          type: RuleGroupType.component,
          orderIndex: 2,
          description: null,
          metadata: null,
          rules: [
            {
              key: 'alert-rule-1',
              name: 'Important information',
              body: 'Use alerts to display important information that requires user attention.',
              orderIndex: 0,
              description: null,
              metadata: null,
            },
          ],
        },
        {
          key: 'alert-dialog',
          name: 'Alert Dialog',
          type: RuleGroupType.component,
          orderIndex: 3,
          description: null,
          metadata: null,
          rules: [
            {
              key: 'alert-dialog-rule-1',
              name: 'Confirmation dialogs',
              body: 'Use alert dialogs for confirmation of critical actions.',
              orderIndex: 0,
              description: null,
              metadata: null,
            },
          ],
        },
      ],
    },
    {
      key: 'content',
      name: 'Content',
      type: RuleGroupType.category,
      orderIndex: 2,
      description: null,
      metadata: null,
      rules: [
        {
          key: 'content-rule-1',
          name: 'Tone of voice',
          body: 'Use active voice. Be direct and clear.',
          orderIndex: 0,
          description: null,
          metadata: null,
        },
      ],
    },
  ],
}
